### ISSUE TITLE
The link to the 'non-chainloader build' points nowhere.

### ISSUE THREAD

**Issue by kitlith** [chaoskagami/skeith#1]
It seems that you don't build a non-chainloader build anymore, so you should remove the link to it?

(Or something is broken and you need to get it building again...)

**Comment by chaoskagami** [comment]
This is known, and people have yelled at me already for it. ;P

No-chain builds have been dropped for now.

**Comment by chaoskagami** [comment]
Readme fixed in 176fb3cf9569a9efa4e000348a58d3d15337ff09 to properly reflect this. Closing.
